your-profile:
  outputs:
    dev:
      type: vertica # Don't change this!
      host: '172.24.2.140'
      port: 5433 # or your custom port (optional)
      username: 'user_finebi_jdbc'
      password: 'userfinebijdbcvert92'
      database: [database name]
      oauth_access_token: [access token]
      schema: [dbt schema]
      connection_load_balance: True
      backup_server_node: [list of backup hostnames or IPs]
      retries: [1 or more]  
      
      threads: [1 or more]
  target: dev