insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('01', 'Комплектация заказа', 'Комплектация заказа');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0101', 'Комплектация заказа', 'Выписанного товара не оказалось в наличии на складе');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0102', 'Комплектация заказа', 'Пересорт, некомплект');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0103', 'Комплектация заказа', 'Качество внешнего вида полученного товара (заводской упаковки и/или упаковки ЭТМ, наклейки, скотч и пр.)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0104', 'Комплектация заказа', 'Механический брак');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0105', 'Комплектация заказа', 'Жалобы на КПП (куски)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0106', 'Комплектация заказа', 'Товар заказан кратно упаковке, приходит россыпью');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0107', 'Комплектация заказа', 'Несоответствие метража КПП');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0108', 'Комплектация заказа', 'Нужного товара нет в наличии на складе');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0109', 'Комплектация заказа', 'Возврат/брак');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0110', 'Комплектация заказа', 'Не устраивает кратность (нужно меньшее кол-во)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0111', 'Комплектация заказа', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('02', 'Срок поставки', 'Срок поставки');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0201', 'Срок поставки', 'Срыв сроков поставки от поставщика');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0202', 'Срок поставки', 'Срыв сроков поставки из-за задержки приема товара на ЛЦ');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0203', 'Срок поставки', 'Срыв сроков поставки при перемещении с ЛЦ в ОП');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0204', 'Срок поставки', 'Срыв сроков поставки при перемещении в ПВЗ СДЭК/ДЛ');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0205', 'Срок поставки', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('03', 'Ассортимент', 'Ассортимент');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0301', 'Ассортимент', 'Неудовлетворенный спрос');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0302', 'Ассортимент', 'Не устраивает кратность (нужно меньшее кол-во)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0303', 'Ассортимент', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('04', 'Карточка товара', 'Карточка товара');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0401', 'Карточка товара', 'Корректность технической информации');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0402', 'Карточка товара', 'Соответствие фото');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0403', 'Карточка товара', 'Корректность сроков поставки в каталоге iPRO');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0404', 'Карточка товара', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('05', 'Программа лояльности', 'Программа лояльности');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0501', 'Программа лояльности', 'Баллы');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0502', 'Программа лояльности', 'Амперы');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0503', 'Программа лояльности', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('06', 'Организация сервиса при доставке', 'Организация сервиса при доставке');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0601', 'Организация сервиса при доставке', 'Прием заявки на доставку');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0602', 'Организация сервиса при доставке', 'Срыв сроков доставки');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0603', 'Организация сервиса при доставке', 'Не учтены комментарии к заявке');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0604', 'Организация сервиса при доставке', 'Удобство сервиса доставки');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0605', 'Организация сервиса при доставке', 'Грубость персонала при доставке (сотрудник ЭТМ, водитель)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0606', 'Организация сервиса при доставке', 'Соблюдение водителями правила о предупреждающем звонке о переносе времени доставки');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0607', 'Организация сервиса при доставке', 'Отказ подъехать к зоне разгрузки');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0608', 'Организация сервиса при доставке', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('07', 'Организация сервиса при самовывозе', 'Организация сервиса при самовывозе');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0701', 'Организация сервиса при самовывозе', 'Удобство организации сервиса');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0702', 'Организация сервиса при самовывозе', 'Скорость обслуживания');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0703', 'Организация сервиса при самовывозе', 'Инфраструктура (удобство, время работы и т.д.)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0704', 'Организация сервиса при самовывозе', 'Отказ в помощи при погрузке, отказ в обслуживании');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0705', 'Организация сервиса при самовывозе', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('08', 'Корректность документооборота', 'Корректность документооборота');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0801', 'Корректность документооборота', 'Возврат д/с');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0802', 'Корректность документооборота', 'Привязка д/c');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0803', 'Корректность документооборота', 'Некорректное оформление документов');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0804', 'Корректность документооборота', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('09', 'Работа персонала', 'Работа персонала');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0901', 'Работа персонала', 'Заменить закрепленного менеджера');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0902', 'Работа персонала', 'Непрофессионализм, некомпетентность менеджера');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0903', 'Работа персонала', 'Несоответствие действий менеджера стандартам обслуживания в торговом зале');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0904', 'Работа персонала', 'Грубость менеджера');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0905', 'Работа персонала', 'Некачественное сопровождение клиента');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0906', 'Работа персонала', 'Жалоба на сотрудников точки, офиса при оформлении документов');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0907', 'Работа персонала', 'Жалоба на сотрудников склада, водителей, охраны');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0908', 'Работа персонала', 'Менеджер не помогает (долго, забывает, не дозвониться, не выполняет обещанного и т.д.)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('0909', 'Работа персонала', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('10', 'Сервис iPRO (сайт)', 'Сервис iPRO (сайт)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1001', 'Сервис iPRO (сайт)', 'Поиск');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1002', 'Сервис iPRO (сайт)', 'Юзабилити');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1003', 'Сервис iPRO (сайт)', 'Неработающие функции');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1004', 'Сервис iPRO (сайт)', 'Регистрация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1005', 'Сервис iPRO (сайт)', 'Быстродействие');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1006', 'Сервис iPRO (сайт)', 'Расчет итоговой стоимости');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1007', 'Сервис iPRO (сайт)', 'Авторизация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1008', 'Сервис iPRO (сайт)', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('11', 'Сервис iPRO (мобильное приложение)', 'Сервис iPRO (мобильное приложение)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1101', 'Сервис iPRO (мобильное приложение)', 'Поиск');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1102', 'Сервис iPRO (мобильное приложение)', 'Юзабилити');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1103', 'Сервис iPRO (мобильное приложение)', 'Неработающие функции');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1104', 'Сервис iPRO (мобильное приложение)', 'Регистрация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1105', 'Сервис iPRO (мобильное приложение)', 'Быстродействие');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1106', 'Сервис iPRO (мобильное приложение)', 'Расчет итоговой стоимости');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1107', 'Сервис iPRO (мобильное приложение)', 'Авторизация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1108', 'Сервис iPRO (мобильное приложение)', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('12', 'Сервис iPRO (адаптивная версия сайта)', 'Сервис iPRO (адаптивная версия сайта)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1201', 'Сервис iPRO (адаптивная версия сайта)', 'Поиск');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1202', 'Сервис iPRO (адаптивная версия сайта)', 'Юзабилити');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1203', 'Сервис iPRO (адаптивная версия сайта)', 'Неработающие функции');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1204', 'Сервис iPRO (адаптивная версия сайта)', 'Регистрация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1205', 'Сервис iPRO (адаптивная версия сайта)', 'Быстродействие');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1206', 'Сервис iPRO (адаптивная версия сайта)', 'Расчет итоговой стоимости');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1207', 'Сервис iPRO (адаптивная версия сайта)', 'Авторизация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1208', 'Сервис iPRO (адаптивная версия сайта)', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('13', 'Цена', 'Цена');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1301', 'Цена', 'Неконкурентоспособные цены');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1302', 'Цена', 'Оперативность предоставления (согласования) спец цены');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1303', 'Цена', 'Невозможность выписки по предложенной цене');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1304', 'Цена', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('14', 'Коммерческие условия', 'Коммерческие условия');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1401', 'Коммерческие условия', 'Запрос на расширение ТК, отсрочки');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1402', 'Коммерческие условия', 'Запрос о заключении договора');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1403', 'Коммерческие условия', 'Другое, связанное с договором/тендером/офертой');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('15', 'Удовлетворенность рассмотрением претензии', 'Удовлетворенность рассмотрением претензии');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1501', 'Удовлетворенность рассмотрением претензии', 'Оперативность реагирования ЭТМ на претензию');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1502', 'Удовлетворенность рассмотрением претензии', 'Качество реагирования ЭТМ на претензию (насколько устроил ответ и действия ЭТМ)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1503', 'Удовлетворенность рассмотрением претензии', 'Отказ в возврате/обмене');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1504', 'Удовлетворенность рассмотрением претензии', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('16', 'Консультация', 'Консультация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1601', 'Консультация', 'Отмена заказа');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1602', 'Консультация', 'Консультация по товару, услуге, заказу');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1603', 'Консультация', 'Просьба закрепить менеджера');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1604', 'Консультация', 'Гарантийный брак');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1605', 'Консультация', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('17', 'Компенсация', 'Компенсация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1701', 'Компенсация', 'Компенсация');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1702', 'Компенсация', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('18', 'Предложение, благодарность', 'Предложение, благодарность');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1801', 'Предложение, благодарность', 'Предложение');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1802', 'Предложение, благодарность', 'Предложение по улучшению iPRO');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1803', 'Предложение, благодарность', 'Благодарность');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1804', 'Предложение, благодарность', 'Другое');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('19', 'Сервис iPRO (сайт, мобильное приложение)', 'Сервис iPRO (сайт, мобильное приложение)');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1901', 'Сервис iPRO (сайт, мобильное приложение)', 'Web-версия: регистрация, поиск, неработающие функции, юзабилити');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1902', 'Сервис iPRO (сайт, мобильное приложение)', 'Мобильное приложение: регистрация, поиск, неработающие функции, юзабилити');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1903', 'Сервис iPRO (сайт, мобильное приложение)', 'Корректность технической информации');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1904', 'Сервис iPRO (сайт, мобильное приложение)', 'Наличие нужного товара в каталоге');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1905', 'Сервис iPRO (сайт, мобильное приложение)', 'Баллы, амперы');
insert into DataPrime.CSI_ElmaSrvcQltyRsns values ('1906', 'Сервис iPRO (сайт, мобильное приложение)', 'Другое');